name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.release.outputs.pr }}
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          token: ${{ secrets.GH_PAT }}

  build_and_release_docker_image:
    name: Build & Release Docker Image
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release.outputs.tag_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platform: |
            linux/amd64
          target: precompiled-pinn-image
          tags: |
            ${{ secrets.DOCKER_REPOSITORY }}:latest
            ${{ secrets.DOCKER_REPOSITORY }}:${{ needs.release.outputs.major }}
            ${{ secrets.DOCKER_REPOSITORY }}:${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}
            ${{ secrets.DOCKER_REPOSITORY }}:${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}.${{ needs.release.outputs.patch }}
          cache-from: "type=registry,ref=${{ secrets.DOCKER_REPOSITORY }}:cache"
          cache-to: "type=registry,ref=${{ secrets.DOCKER_REPOSITORY }}:cache,mode=max"